version 0.0
os: linxu

files:
  - source: laravel/index.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    mode: 755
    type:
     - file

hooks:
  BeforeInstall:
    - location: scripts/web-stop.sh
  AfterInstall:
    - location: scripts/web-start.sh         