version 0.0
os: linxu

files:
  - source: laravel/index.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    group: 644
    type:
     - file

hooks:
  BeforeInstall:
    - location: scripts/web-stop.sh
    - location: scripts/delete-old-index.sh
  AfterInstall:
    - location: scripts/web-start.sh