version 0.0
os: linux

files:
  - source: laravel/index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
  AfterInstall:
    - location: scripts/web-start.sh
      timeout: 300
      runas: root